language: ruby
rvm: 2.3.1
jdk: oraclejdk8

install:
   - gem update --system
   - gem --version
   - bundle install
script:
  - jekyll build
  - htmlproofer ./_site --check-html
env:
  global:
    -NOKOGIRI_USE_SYSTEM_LIBRARIES=true
